### PR TITLE
Added Vagrant support and Misc fixes

### PR DESCRIPTION
**Pull request by PrahlM93**
* Added Vagrant support
* Removed reliance on supervisor
* Set Docker to use Ubuntu 14.04.4 instead of latest
* Updated requirements.txt
* Rebranded from Swagger to StackFocus
* Updated boostrap and jquery
* Fixed mobile view
* Changed HOST_NAME variable to ip.stackfocus.org
* Removed unnecessary -URI from PowerShell command
* New screenshots

### CODE REVIEW

**Comment by PrahlM93** [comment]
@thatarchguy, let me fix the build.

**Comment by PrahlM93** [comment]
@thatarchguy I'm done now with my commits

**Comment by PrahlM93** [comment]
@thatarchguy, ready for review.

**Comment by thatarchguy** [comment]
Excellent job. Thank you for understanding my concerns about the Docker stuff

**Comment by thatarchguy** [comment]
[LGTM](http://lgtm.in/i/gsYCFkRGn)

[:+1:](http://lgtm.in/u/gsYCFkRGn)

**Pull request merged**
